project_id = "weboot-cursos"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]

[db]
port = 54322
major_version = 17

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000/confirmacao",
  "http://localhost:3000/redefinir-senha",
  "http://127.0.0.1:3000/confirmacao",
  "http://127.0.0.1:3000/redefinir-senha",
]
enable_signup = true

[storage]
enabled = true
file_size_limit = "50MiB"
